### ISSUE TITLE
Implement Montgomery modular inverse algorithm

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/dusk-corretto#9]
After continuous review of the possible algorithms, the decided algorithm will be the one implemented by 'E. Savas, C. K. Koc',  :- 'http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.75.8377&rep=rep1&type=pdf'

The chosen `Montgomery modular inverse algorithm` divides the fore computation into two parts, Phase 1 & Phase 2.

Problems to address: 
- Outline values for both phases s.t. they multiply to 1 (mod p)
- Determine whether the output values will be even or odd. Initial even values must be divided by 2 and then 2p is used for modulo

**Comment by CPerezz** [comment]
PhaseI is already implemented on 77bc018. Waiting to implement phaseII and then finish the whole IverseMod Montgomery algorithm.

**Comment by Bounce23** [comment]
The values needed for use in both cases are already computed. 
The are tested to correctly equate as: `(a*a^-1 (mod p)) ≡ 1 (mod p)`

**Comment by CPerezz** [comment]
Phase II was implemented successfully on 457ef6e 
Then the final stage of the algorithm implementation was started on 22b13e0, but there was a problem with the impossibility of performing `2^k` operation, so now it's needed an implementation for `FieldElement`. Will open an issue for it.

**Comment by CPerezz** [comment]
At this point, Implement the Savas & Koç modification of this algorithm to increase
the performance of the operation will be great.
So maybe we can implement the algorithm and then benchmark both solutions to see which performs
better with our `FieldElement` definition.

Will open a new issue for this purposes since this one can be closed with the `Kalinski Modular inverse algorithm implementation`.

Tools for the second algorithm implementation
were builded on 54152f2 and allowed us to close #11
